### ISSUE TITLE
Support for `\psGTriangle`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#25]
The `pstricks-add` package adds _Gouraud shading_, it would be nice to have support for this.

```latex
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress} % only for the test examples, can later be empty
\documentclass[parskip=half-,DIV=13]{scrartcl}
\usepackage{pstricks}
\usepackage{pstricks-add}
\pagestyle{empty}
\begin{document}
% from doc
\psset{unit=0.75cm}
\begin{pspicture}(0,-.25)(10,10)
  \psGTriangle(0,0)(5,10)(10,0){red}{green}{blue}
\end{pspicture}

\begin{pspicture}(0,-.25)(10,10)
  \psGTriangle*(0,0)(9,10)(10,3){black}{white!50}{red!50!green!95}
\end{pspicture}

\begin{pspicture}(0,-.25)(10,10)
  \psGTriangle*(0,0)(5,10)(10,0){-red!100!green!84!blue!86}
                               {-red!80!green!100!blue!40}
                               {-red!60!green!30!blue!100}
\end{pspicture}

\definecolor{rose}{rgb}{1.00, 0.84, 0.88}
\definecolor{vertpommepasmure}{rgb}{0.80, 1.0, 0.40}
\definecolor{fushia}{rgb}{0.60, 0.30, 1.0}
\begin{pspicture}(0,-.25)(10,10)
  \psGTriangle(0,0)(5,10)(10,0){rose}{vertpommepasmure}{fushia}
\end{pspicture}
\end{document}
```

```raw
(/usr/local/texlive/2021/texmf-dist/tex/latex/translations/translations-basic-d
ictionary-english.trsl) [1./luapstricks.lua:467: Unknown name "rg"
stack traceback:
	[C]: in function 'error'
	./luapstricks.lua:467: in upvalue 'lookup'
	./luapstricks.lua:2723: in upvalue 'execute_tok'
	./luapstricks.lua:2753: in upvalue 'execute_ps'
	./luapstricks.lua:2814: in function <./luapstricks.lua:2811>
	[C]: in function 'vf.node'
	./luapstricks.lua:2804: in function <./luapstricks.lua:2795>.
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

l.33 \end{pspicture}
```

Expected output:

![test-pseudo-trans-crop-1](https://user-images.githubusercontent.com/2289461/131385661-a3f68e54-97c7-420d-9a5c-83d11ff5fc5f.png)
![test-pseudo-trans-crop-2](https://user-images.githubusercontent.com/2289461/131385652-d7169d53-94fe-40b6-b82b-17b40941169f.png)

**Comment by zauguin** [comment]
There are basically two parts of this:

 * [ ] Currently `\psGTriangle` expects the internal representation of it's color arguments to have the form which is used in `dvips`, this has to be adapted to allow for the PDF based representation used in LuaLaTeX. (This causes the actual error message you encountered: `rg` is a PDF operator to set the RGB color, pstricks doesn't expect it and ends up passing it on to PostScript where it isn't known (The PostScript equivalent (more or less) would be `setrgbcolor`).
 * [ ] Then the support for the shading operators has to be implemented. This isn't too hard since they can mostly just passed on to PDF where basically the same constructs exists, but some elements most be normalized first.

**Comment by pablgonz** [comment]
I get it, basically it should be adapted from pstricks-add to support luapstricks (if I understand correctly).

**Comment by hvoss49** [comment]
All examples are now ok. I'll upload all changed files (pstricks.tex|pro, pstricks-add.tex) to CTAN later.
