### ISSUE TITLE
\pstVerb

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#26]
No color in the output and no error:

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass[border=5mm]{standalone}
\usepackage{pstricks}
\newcount\WL \unitlength.75pt
\def\WaveToPS#1{%
  \definecolor{tmp}{wave}{#1}\extractcolorspec{tmp}\tmp
  \expandafter\convertcolorspec\tmp{rgb}\tmp \expandafter\WaveToPSi\tmp,}
\def\WaveToPSi#1,#2,#3,{\pstVerb{/Red {#1} def /Green {#2} def /Blue {#3} def}}
\pstVerb{/Corr {dup 0 gt {Gamma exp} if } def }
\definecolor[ps]{lambda}{rgb}{Red Corr Green Corr Blue Corr}
\begin{document}
\begin{picture}(510,70)(310,-10)\sffamily\tiny
  \linethickness{1.25\unitlength}\WL=360
  \pstVerb{/Gamma .8 def}\multiput(320,0)(1,0){456}{%
    \WaveToPS{\the\WL}{\color{lambda}\line(0,1){50}}\global\advance\WL1}%
  \linethickness{0.25\unitlength}\WL=360
  \multiput(320,0)(20,0){23}{%
    \picture(0,0)
      \line(0,-1){5}\multiput(5,0)(5,0){3}{\line(0,-1){2.5}}%
      \put(0,-10){\makebox(0,0){\the\WL}}\global\advance\WL20
    \endpicture}%
\end{picture}
\end{document}
```

<img width="612" alt="Bildschirmfoto 2021-08-30 um 21 39 58" src="https://user-images.githubusercontent.com/12891199/131395434-beaad23a-bd88-4896-bf56-bfc147e2a162.png">

expected:

<img width="610" alt="Bildschirmfoto 2021-08-30 um 21 36 47" src="https://user-images.githubusercontent.com/12891199/131395323-a138f909-1971-483b-a673-2166a0f80253.png">

**Comment by zauguin** [comment]
This is complicated, especially since the color is applied with `\color`, so it is never seen by the PostScript code but only handled inteernally by LaTeX (which in this case generates invalid PDF code). Any fix would involve patching the color backend, but since the classical color backends might relativly soon switch to a l3color based system and the handling of PS colors there isn't decided yet, it's not a good time to mess with that.

**Comment by pablgonz** [comment]
@zauguin This affects  #25?

**Comment by hvoss49** [comment]
rewritten in PS code
