### ISSUE TITLE
Extend support for `pst-plot`

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#46]
I didn't find the right way to make the request for this, so here's my previous analysis.

The package loads:

- `pstricks` (base) which is (I believe) fully supported
- `pst-tools` is fully supported  #28
- `pstricks-add` which depends on `pst-math`, `pst-arrow`, `pst-3d` (full supported), `pst-plot` (circular dependency) and `pst-node` (almost completely supported https://github.com/zauguin/luapstricks/issues/18#issuecomment-910226519). 
This package (`pstricks-add`)  itself is almost fully supported except for https://github.com/zauguin/luapstricks/issues/26#issue-983136474 , https://github.com/zauguin/luapstricks/issues/25#issue-983069985 and https://github.com/zauguin/luapstricks/issues/24#issuecomment-908568396.

As the depencies are (mostly) fulfilled, I tried to check the support for `pst-plot`, here I got a bit (quite) complicated so I had to split the documentation into three parts. To summarize:

- Part I (Basic commands), pages 4-6 full suported [pst-plot-doc-p4-6.zip](https://github.com/zauguin/luapstricks/files/7103419/pst-plot-doc-p4-6.zip)
- Part II (New commands), pages 7-24 almost everything is unsupported :( [pst-plot-doc-p7-24.tex.zip](https://github.com/zauguin/luapstricks/files/7103421/pst-plot-doc-p7-24.tex.zip)
- Part II (New or extended options), page 25 onwards full suported [pst-plot-doc-p25-93.zip](https://github.com/zauguin/luapstricks/files/7103418/pst-plot-doc-p25-93.zip)

Sorry for not being able to create an MWE for part II, the errors returned by the compilation were not very understandable but they are related to `savedata`, `readdata` and `psBoxplot`, not to the `psgraph` environment (as such).

I can only attach the file that is failing in a complete way 

[pst-plot-doc-p7-24.tex.zip](https://github.com/zauguin/luapstricks/files/7103421/pst-plot-doc-p7-24.tex.zip)

PS: I spent a lot of time cutting to come up with this, it really was my best effort for this great project.

Saludos

**Comment by zauguin** [comment]
@pablgonz Thanks.

The underlying issue is `\psBoxplot@i` and `\psBoxplot@ii` using the PostScript name `NArray` for a variable. This overwrites the normal definition of `NArray` in pstricks, therefore breaking code which relies on that definition.

Of course with dvips this isn't an issue since there the redefinition is local and therefore reset at the end of the special, but luapstricks only dies global assignments and therefore breaks.

IMO the use of this name is confusing anyway (especially since the same package also uses the normal definition of `NArray` in other parts) and therefore the best approach would be to rename the variables, but of course the maintainer of the package might disagree and there are some other possible options.

**Comment by hvoss49** [comment]
It is fixed in new `pst-plot`

**Comment by hvoss49** [comment]
I just compiled the _complete_ document with `lualatex` and can report "Success!" :-).  https://hvoss.org/PSTexa/pst-plot-doc.pdf
