### ISSUE TITLE
`psvectorian` and Unknown name "initclip"

### ISSUE THREAD

**Issue by pablgonz** [zauguin/luapstricks#54]
I have seen this message before with the starred environment (https://github.com/zauguin/luapstricks/issues/1#issue-974020739) and when using the `psvectorian` package, the following appears again :(

```latex
% arara: latex
% arara: dvips
% arara: ps2pdf: { options : [ -dALLOWPSTRANSPARENCY -dPDFSETTINGS=/prepress -dNOSAFER] }
% arara: clean: { extensions : [ aux, log, dvi, ps ] }
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{}
\documentclass[pstricks,border=12pt]{standalone}
\usepackage{psvectorian}
\begin{document}

\begin{pspicture}(-5,-5)(5,5)
\psframe(-5,-5)(5,5)
%haut+bas
\rput[tl](-3,5){\psvectorian[width=6cm]{71}}
\rput[bl](-3,-5){\psvectorian[width=6cm,flip]{71}}
%coins
\rput[tl](-5,5){\psvectorian[width=2cm]{63}}
\rput[tr](5,5){\psvectorian[width=2cm,mirror]{63}}
\rput[bl](-5,-5){\psvectorian[width=2cm,flip]{63}}
\rput[br](5,-5){\psvectorian[width=2cm,flip,mirror]{63}}
% cotes
\rput[bl]{-90}(-5,3){\psvectorian[width=6cm]{46}}
\rput[bl]{90}(5,-3){\psvectorian[width=6cm]{46}}
%texte+soulignement+chapeau
\rput(0,0){\Huge LuaPStricks}
\rput[t](0,-0.5){\psvectorian[width=5cm]{75}}
\rput[b](0,0.5){\psvectorian[width=5cm]{69}}
%oiseaux
\rput[tr]{-30}(-1,2.5){\psvectorian[width=2cm]{57}}
\rput[tl]{30}(1,2.5){\psvectorian[width=2cm,mirror]{57}}
\end{pspicture}

\end{document}
```

```raw
[1./luapstricks.lua:569: Unknown name "initclip"
stack traceback:
	[C]: in function 'error'
	./luapstricks.lua:569: in upvalue 'lookup'
	./luapstricks.lua:3023: in upvalue 'execute_tok'
	./luapstricks.lua:3053: in function <./luapstricks.lua:3051>
	(...tail calls...)
	./luapstricks.lua:3053: in upvalue 'execute_ps'
	./luapstricks.lua:3114: in function <./luapstricks.lua:3111>
	[C]: in function 'vf.node'
	./luapstricks.lua:3104: in function <./luapstricks.lua:3095>.
<inserted text> BAD
   
l.31 \end{pspicture}
                  
? 
```

![Captura de pantalla -2021-09-04 12-44-59](https://user-images.githubusercontent.com/2289461/132102096-ca601d5a-cad2-446b-9f83-366b52e86598.png)

Can anything be done from the `luapstricks` side to support this?

**Comment by zauguin** [comment]
`initclip` can't easily be mapped into PDF since it allows to extend the current clipping path which is conceptually not supported in the PDF graphics model, so supporting it would require tracking a lot of global state and then attempts to reestablish all current groups. This is particularly hard since it might require interacting with groups which weren't started by PostScript code in the first place.

Even ignoring that, the usage of `initclip` here is somewhat odd and can lead to issues: Take e.g.

```
\documentclass[pstricks,border=12pt]{standalone}
\usepackage{psvectorian}
\begin{document}

\begin{pspicture}(-5,-5)(5,5)
\psclip{\pscircle[linestyle=none]{2}}
  \rput(0, 0){\psvectorian[height=10cm]{10}}
\endpsclip\pscircle[linewidth=0.01]{2}
\end{pspicture}

\end{document}
```
which should normally clip the graphics to a circle in the middle. Instead you get

![image](https://user-images.githubusercontent.com/962229/132192954-2972fb4c-11ed-42fb-ace9-5deca1433dd2.png)
where only one circle at the top gets clipped.

Therefore I think that this would be best addressed by changing `psvectorian` to replace it's usage of `initclip` with `gsave/grestore` pairs. I've uploaded a `psvectorian.pro` implementing this.

**Comment by pablgonz** [comment]
Ohh, I didn't expect this, you have rewritten `psvectorian.pro` and everything is perfect. Maybe @hvoss49  can have communication with the author.

**Comment by hvoss49** [comment]
> Ohh, I didn't expect this, you have rewritten `psvectorian.pro` and everything is perfect. Maybe @hvoss49 can have communication with the author.

already done ... and new version uploaded to CTAN
