### ISSUE TITLE
PostScript Colors 

### ISSUE THREAD

**Issue by hvoss49** [zauguin/luapstricks#60]
Is there any chance that this can be fixed on the Lua side? Actually the "PS color" is written directly into the pdf: 
`rgb tx@addDict begin Red Green Blue end`

```
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress} % only for the test examples, can later be empty
\documentclass[pstricks,border=12pt]{standalone}
\usepackage{pstricks-add}
\begin{document}

\definecolor[ps]{bl}{rgb}{tx@addDict begin Red Green Blue end}

\psset{unit=1bp}
\begin{pspicture}(0,-30)(400,100)
\multido{\iLAMBDA=0+1}{400}{%
  \pstVerb{
    \iLAMBDA\space 379 add dup /lambda exch def tx@addDict begin wavelengthToRGB end   
  }%
  \psline[linecolor=bl](\iLAMBDA,0)(\iLAMBDA,100)% 
}
\psaxes[yAxis=false,Ox=350,dx=50bp,Dx=50]{->}(-29,-10)(420,100) 
\uput[-90](420,-10){$\lambda$[\textsf{nm}]}
\end{pspicture}

\end{document}
```

**Comment by pablgonz** [comment]
Related to https://github.com/zauguin/luapstricks/issues/26#issuecomment-912781684

**Comment by zauguin** [comment]
> Is there any chance that this can be fixed on the Lua side?

It could be fixed there, but I think it would be cleaner if we would handle this in `\c@lor@to@ps`. After all, converting such a color expression to a PostScript color really should just give the PostScript code, adding an indirection where it is treated as an almost PDF color doesn't make sense. This could also be used as an opportunity to handle normal colors with their normal operators instead of always using `setpdfcolor` which seems overly complicated in hindsight, leaving `setpdfcolor` for the "more interesting" cases.

Of course we could still do that in Lua, then we would provide a Lua version of `\c@lor@to@ps` (either with that name directly or more likely as `\luaPSTcolor` or something to avoid having to deal with the delimited argument).

**Comment by zauguin** [comment]
I implemented something along these lines in the `colors` branch: `\c@lor@to@ps` is replaced by a small wrapper around a Lua command which also replaces the code in pstricks.pro to remap cmyk and rgb colors to their normal commands. This made it much cleaner to also handle the PostScript colors, but similar code could also be used with the old approach.

Do you have any preference either way?

**Comment by hvoss49** [comment]
Looks good! Except the following example. It still writes the complete string into the PDF:

```
%% ==error==
\RequirePackage{pdfmanagement-testphase}
\DeclareDocumentMetadata{uncompress}
\documentclass[border=5mm]{standalone}
\usepackage{pstricks}
\newcount\WL \unitlength.75pt
\def\WaveToPS#1{%
  \definecolor{tmp}{wave}{#1}\extractcolorspec{tmp}\tmp
  \expandafter\convertcolorspec\tmp{rgb}\tmp \expandafter\WaveToPSi\tmp,}
\def\WaveToPSi#1,#2,#3,{\pstVerb{/Red {#1} def /Green {#2} def /Blue {#3} def}}
\pstVerb{/Corr {dup 0 gt {Gamma exp} if } def }

\definecolor[ps]{lambda}{rgb}{ Red Corr Green Corr Blue Corr }

\begin{document}
\begin{picture}(510,70)(310,-10)\sffamily\tiny
  \linethickness{1.25\unitlength}\WL=360
  \pstVerb{/Gamma .8 def}%
  \multiput(320,0)(1,0){456}{%
    \WaveToPS{\the\WL}{\color{lambda}\line(0,1){50}}\global\advance\WL1}%
  \linethickness{0.25\unitlength}\WL=360
  \multiput(320,0)(20,0){23}{%
    \picture(0,0)
      \line(0,-1){5}\multiput(5,0)(5,0){3}{\line(0,-1){2.5}}%
      \put(0,-10){\makebox(0,0){\the\WL}}\global\advance\WL20
    \endpicture}%
\end{picture}
\end{document}
```

**Comment by zauguin** [comment]
> Looks good! Except the following example. It still writes the complete string into the PDF:

Well, it doesn't use pstricks to set the colors so are opportunities are somewhat limited. So this requires patching `xcolor` to pass such colors to `luapstricks`, but that is somewhat incompatible with how `xcolor` works (since on LuaTeX it sets color using colorstacks and they require colors to be fixed PDF commands). Additionally there is `luacolor` to think about. While `luacolor` should make this simpler (since it could be adapted to insert arbitrary nodes to set the color) it makes uses like this even more complicated since `luacolor` in some cases can "merge" sections colored in the "same color" (from TeX's point of view), so if the colors actually change without the tokenlist seen by TeX changing, then the change might not get adopted.

**Comment by hvoss49** [comment]
Ok then let it be and I'll create a PSTricks compatible example.

**Comment by zauguin** [comment]
@hvoss49 Any thought about merging (or not) of the `colors` branch?

**Comment by hvoss49** [comment]
Can be merged! All is fine as far as I can see!
