### ISSUE TITLE
Processing of eps files via Lua

### ISSUE THREAD

**Issue by rolfn** [zauguin/luapstricks#67]
Hello Marcel,
Thank you for the great `luapstricks`.

My following hints are not a bug report, but a suggestion that is still unfinished. There are two options for inserting eps files when using LuaLaTeX:

* Package `graphics` with option `mps` (via `\convertMPtoPDF` from `supp-pdf.mkii`) for very simple eps files (e.g. from Metapost).
* Via package `epstopdf`, which uses an external conversion program.

The second variant works in principle in all cases, but is not always problem-free because of the external program call. It would now be conceivable to add an additional option to the graphics configuration file `luatex.def` (e.g. `luapst`) and to manage eps files using Lua code with the help of `luapstricks.lua`. I am unsure whether this is easily possible and whether it makes sense. It's just a thought experiment. Thank you for an answer.

Rolf

**Comment by zauguin** [comment]
Pretty much by design this implements a certain subset and not the complete PostScript language. Now there are some commands which aren't implement just because they didn't show up yet so they don't have any priority, but there are also some concepts which would lead to a significant overhead which IMNSHO is not worth the benefit. (E.g. support for embedded Type 1 fonts would be a lot of work for a feature which is almost never used in a traditional OpenType based LuaLaTeX workflow / embedded bitmap graphics would require quite some parsing and decoding work, only to reencode the files to be passed to LuaTeX and then being reparsed, while the same formats can already be natively embedded through LuaTeX code)
Many of these things can be compensated by rather minor changes to the PostScript code which makes them great for PSTricks where such constructs are often isolated into packages anyway and can be adapted on that level, while they would be rather problematic for EPS files which can contain arbitrary PS from sources we can't control.

So basicallt we can't (at least not without a lot of work) replace `epstopdf` and could at best provide a moderately more powerful version of `\convertMPtoPDF` (which probably still wouldn't work  for most non MetaPost files because of font issues).

**Comment by rolfn** [comment]
I understand. Thank you.
