### ISSUE TITLE
\luaPST creates unwanted empty lines

### ISSUE THREAD

**Issue by u-fischer** [zauguin/luapstricks#79]
extracted from https://tex.stackexchange.com/q/632563/2388

`\luaPST` interferes with the output routine and so `\clearpage\newpage` creates an empty page:

~~~~
\documentclass{book}
\directlua{require'luapstricks'}%
\luaPST{}
\begin{document}

\clearpage
\newpage

blub
\end{document}
~~~~

gives 

     Output written on test-utf8.pdf (2 pages, 3115 bytes).

**Comment by zauguin** [comment]
The underlying problem is that `\luaPST` needs to create proper content nodes and not just whatsits in order to shipout some constructs. Actually adding these to the page makes TeX determine that the page isn't empty, therefore the next `\clearpage` or `\newpage` will ship a page. If there isn't actually anything visually drawn than the page is empty. For compatibility we try to suppress this by adding the nodes we add to the page without going through the normal machinery such that TeX doesn't notice that there is something on the page, but when `\clearpage` invokes the output routine and not shipout the page, everything gets put back, this time through normal systems and therefore our nodes are seen by TeX.

Now we could add yet another weird trick to avoid this (E.g. we might be able to hide as leaders, but we have to make sure that they aren't discarded)  but I'm wondering if maybe it's better to address the problem at it's root: The use of `\luaPST` for very different things. After all, for typical uses of `\luaPST` it makes a lot of sense to start a new page: There is no reason why some drawing shouldn't be allowed to be alone on a page. But we have the same command being used to send small snippets with settings to the PostScript interpreter and they shouldn't get this handling. But since they never have to draw anything, there is no issue with keeping them in whatsits. So maybe it would be better to have separate commands: One command which is able to start a page(or for compatibility as right now tries but not guarantees not to start a new page) and can draw, while a second command behaves like a whatsit but is not allowed to issue draw commands.

I experimented with that approach in [a branch](https://github.com/zauguin/luapstricks/tree/pstVerbset). @hvoss49 Could you take a look, especially at c1c5a942cfb8b4717843b41edf4135e336d34466? Ignoring the naming for now, is that a direction we could take or would it break too much? In order to avoid having to change existing code, we could also make \pstVerb default to the \pstVerbset behavior when invoked before \begin{document} / when invoked in outer vmode with an empty page?

**Comment by hvoss49** [comment]
running `lualatex --shell-escape test` I get

```
[Loading MPS to PDF converter (version 2006.09.02).]
) [1./luapstricks.lua:3990: ./luapstricks.lua:2097: nocurrentpoint
stack traceback:
	[C]: in function 'error'
	./luapstricks.lua:3990: in function 'execute_string'
	./luapstricks.lua:4042: in function <./luapstricks.lua:4034>.
<argument> ...shipout_finalize_box: \cs_set_eq:NN \protect \exp_not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                                                                    \__shipout_drop_firstpage_specials: \set@typeset@protect \hook_use:n {shipout/after}
l.13 \end{document}
```

test.tex has only `\psline[linecolor=red](10,10)`

**Comment by hvoss49** [comment]
> I experimented with that approach in [a branch](https://github.com/zauguin/luapstricks/tree/pstVerbset). @hvoss49 Could you take a look, especially at [c1c5a94](https://github.com/zauguin/luapstricks/commit/c1c5a942cfb8b4717843b41edf4135e336d34466)? Ignoring the naming for now, is that a direction we could take or would it break too much? In order to avoid having to change existing code, we could also make \pstVerb default to the \pstVerbset behavior when invoked before \begin{document} / when invoked in outer vmode with an empty page?

`\pstVerb` is heavily used in a lot of packages and situations. And, by the way: I cannot see that the above behaviour is a _real_. problem.

**Comment by u-fischer** [comment]
@hvoss49  my bug report came from a real problem (reported on tex.sx: https://tex.stackexchange.com/questions/632563/lualatex-pstricks-and-maketitle-conflict): \maketitle contains a \newpage\clearpage and so simply loading pstricks leads to an empty page before the title:

~~~~
\documentclass{book}
\usepackage{pstricks}
\author{me}
\title{title}
\begin{document}
\maketitle
\end{document}
~~~~

**Comment by hvoss49** [comment]
I know it, but this fix:

```
\documentclass{book}
\usepackage{pstricks}
\author{me}
\title{title}
\begin{document}

{\let\clearpage\relax\maketitle}

\tableofcontents
\chapter{foo}
\clearpage
\section{bar}
\end{document}
```

is much more easier than than changing a lot of code in luapstricks. This is what I called "not a real problem".
No more no less.

**Comment by zauguin** [comment]
While debugging this I found a related issue where the current approach doesn't work: Sometimes we insert an additional `\topskip` (e.g. in the psdot test, not quite sure what triggers it) So I'll look into doing weird stuff with leaders instead, if that works out it might fix this issue anyway.

**Comment by zauguin** [comment]
As an update on this, my leader experiments failed horribly but with new engine changes available probably starting with TeX Live 2022 there will be a much nicer fix.

**Comment by u-fischer** [comment]
ah, did that trigger your question on the list? ;-).

**Comment by zauguin** [comment]
> ah, did that trigger your question on the list? ;-).

It was the reason for raising it now, but I missed that functionality multiple times before.

**Comment by pablgonz** [comment]
> As an update on this, my leader experiments failed horribly but with new engine changes available probably starting with TeX Live 2022 there will be a much nicer fix.

The good thing is that TeX Live 2022 is already here...the bad thing is to find the time for these things :D

**Comment by zauguin** [comment]
> the bad thing is to find the time for these things :D

The fix is already waiting in the `new_luatex` branch so pushing it doesn't take much time ... of course that doesn't help if you don't remember to do it. I'll make a release.

**Comment by pablgonz** [comment]
@zauguin This is already fixed? it works OK for me.

**Comment by zauguin** [comment]
It's fixed in the repo but not in the released version.

**Comment by pablgonz** [comment]
@zauguin Should it be closed now?
