### ISSUE TITLE
pstricks inside XObjects fail

### ISSUE THREAD

**Issue by u-fischer** [zauguin/luapstricks#81]
the animate package uses XObjects and if one use pstricks in it is fails with luapstricks: https://tex.stackexchange.com/q/646555/2388

The error can also be reproduced with this shorter example, which compiles fine with latex+dvips+ps2pdf but fails with lualatex:

~~~~
\DocumentMetadata{}
\documentclass[]{article}

\usepackage{pstricks}

\begin{document}

\ExplSyntaxOn
\pdfxform_new:nnn {test}{}{
  \begin{pspicture}(0,0)(1,1)
      \psframe(0,0,)(1,1)
  \end{pspicture}
  blub
  }

xxx \pdfxform_use:n {test}  
\ExplSyntaxOff
\end{document}
~~~~

~~~~
)...2022/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4048: ...2022/texmf
-dist/tex/lualatex/luapstricks/luapstricks.lua:794: Unknown name "tx@Dict"
stack traceback:
	[C]: in function 'error'
	...2022/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4178: in function <
...2022/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4153>
	[C]: in function 'vf.node'
	...2022/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4146: in function <
...2022/texmf-dist/tex/lualatex/luapstricks/luapstricks.lua:4137>.
<recently read> \l__pdf_backend_tmpa_box 
~~~~

**Comment by hvoss49** [comment]
The pro files are not known.

```
\RequirePackage{pdfmanagement-testphase}
\DocumentMetadata{}
\documentclass[]{article}
\usepackage{pstricks}
\begin{document}

\ExplSyntaxOn
\pdfxform_new:nnn {test}{}{
  \pstheader{pstricks.pro}%%%%%%%  works
  \pspicture(0,0)(1,1)
      \psframe(0,0,)(1,1)
  \endpspicture
  blub
}

xxx \pdfxform_use:n {test}  
\ExplSyntaxOff
\end{document}
```

**Comment by zauguin** [comment]
It's an ordering issue mostly: `pstricks` gets initialized in some whatsits, but the XForm is build before the first page is shipped so it's not initialized yet.

**Comment by zauguin** [comment]
Originally luapstricks used to evaluate headers in a special way which did not require whatsits or to be delayed until shipout. This was changed some months ago since the new behavior it's more compatible with DVI drivers. We could fix this by restoring the old behavior, but it can break code which relies on the ordering between `\luaPST` and `\luaPSTheader` code.

So at least on the `luapstricks` side I made it now optional: When `\pstheader` is defined as `\luaPSTheader` (which is now an alias for `\luaPST direct file`), then the current behavior is preserved and `\pstVerb`s and `\pstheader`s are correctly ordered, but immediate XObjects on the first page break.

When `\pstheader` gets defined as `\luaPST immediate file`, then they get executed immediately and therefore generally before `\pstVerb`, but therefore they fix XObjects.

I think that such a change to `\pstheader` should be relatively safe (especially since it's quite similar to what we had until three(-ish) months ago, but I think it needs some testing before making it the default.
